export { authService } from '@/services/auth'
export { marketDataProvider, type MarketDataProvider } from '@/services/market-data'
export { walletService, walletProvider, type WalletProvider } from '@/services/wallet'
export { paymentProvider, type PaymentProvider } from '@/services/payment'
export { tradeService, tradingProvider, type TradingProvider } from '@/services/trades'
export { botService, botProvider, type BotProvider } from '@/services/bots'
export { copyTradingService, copyTradingProvider, type CopyTradingProvider } from '@/services/copy-trading'
export { notificationService, supportService } from '@/services/notifications'
export { adminService } from '@/services/admin'
